### PR TITLE
Setup gradec releases

### PR DESCRIPTION
**Pull request by ayazhafiz**
Releases will be created for x86 linux, x64 macOS, and windows.

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@timothycobrien ptal

**Comment by ayazhafiz** [comment]
It's a ridiculous problem with yarn: https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288/24

**Comment by timothycobrien** [comment]
Why not use npm @ayazhafiz ?

**Comment by ayazhafiz** [comment]
preference

**Pull request merged**
